import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "../components/sidebar/sidebar";
import "@/vendors/myicons/dist/myicons.scss";
import "./globals.scss";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " flex h-screen"}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
